spring-boot:
  nameOverride: "booking-service"
  fullnameOverride: "booking-service"
  image:
    repository: ghcr.io/bookablecom/booking-service
    tag: 0.0.20
  imagePullSecrets:
    - name: "dockerconfigjson-github-com"
  extraEnv:
    CONFIG_SERVER_URI: http://config-server:8080
  name: booking-service
  healthChecks:
    enabled: false
    readinessProbe:
      httpGet:
        path: /actuator/health/readiness
        port: http
        httpHeaders:
          - name: authorization
            value: ""
      initialDelaySeconds: 120
      periodSeconds: 40
      timeoutSeconds: 15
      failureThreshold: 60
    livenessProbe:
      httpGet:
        path: /actuator/health/liveness
        port: http
        httpHeaders:
          - name: authorization
            value: ""
      initialDelaySeconds: 120
      periodSeconds: 40
      timeoutSeconds: 15
      failureThreshold: 60
  replicaCount: 1
  spring:
    profiles:
      active: default
traefik-ingress:
  ingress:
    match: "Host(`api.bsgrd.com`) && Path(`/bookings`, `/bookings/{id}`, `/organizations/{id}/bookings`)"
    tls:
      enabled: true
      resolver: "letsencrypt"
  service:
    name: "booking-service"
    port: 8080
