apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      {{- if .Values.mesh.enabled }}
      annotations:
        linkerd.io/inject: enabled
      {{- end}}
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ .Chart.Name }}
      imagePullSecrets:
        - name: dockerconfigjson-github-com
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: GITHUB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.github.secret.name }}
                  key: GITHUB_USERNAME

            - name: GITHUB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.github.secret.name }}
                  key: GITHUB_PASSWORD

            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.vault.secret.name }}
                  key: VAULT_TOKEN

            - name: CONFIG_REPO_URI
              value: {{ .Values.github.repo }}

            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.spring.profiles.active }}

            - name: VAULT_HOST
              value: {{ .Values.vault.host }}