apiVersion: v1
kind: Secret
metadata:
  name: config-server-github-secret
  annotations:
    kubernetes.io/service-account.name: {{ .Values.name }}
type: "Opaque"
stringData:
  GITHUB_USERNAME: {{ .Values.github.username }}
  GITHUB_PASSWORD: {{ .Values.github.password }}