{{- if .Values.github.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.github.secret.name }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.name }}
type: "Opaque"
stringData:
  GITHUB_USERNAME: {{ .Values.github.secret.username }}
  GITHUB_PASSWORD: {{ .Values.github.secret.password }}
{{- end }}