{{- if .Values.vault.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.vault.secret.name }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.name }}
type: "Opaque"
stringData:
  VAULT_TOKEN: {{ .Values.vault.secret.token }}
{{- end }}