apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spring-boot.fullname" . }}-env
  labels:
    app: {{ include "spring-boot.fullname" . }}
data:
  {{- toYaml .Values.extraEnv | nindent 2 }}