replicaCount: 1

image: ghcr.io/bookablecom/config-server:2.1.0

fullnameOverride: "config-server"
name: "config-server"

mesh:
  enabled: false

serviceAccount:
  create: true

service:
  type: ClusterIP
  port: 8080

configserver:
  repo_uri: https://github.com/bookablecom/configurations

github:
  username: "kasper.bisgaard@live.com"
  password: "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"

vault:
  host: vault.default.svc.cluster.local
  token: "root"