replicaCount: 1

image: ghcr.io/bookablecom/config-server:2.2.1

fullnameOverride: "config-server"
name: "config-server"

spring:
  profiles:
    active: git,vault

mesh:
  enabled: true

serviceAccount:
  create: true

service:
  type: ClusterIP
  port: 8080

configserver:
  repo_uri: https://github.com/bookablecom/configurations

github:
  username: ""
  password: ""

vault:
  host: vault.default.svc.cluster.local
  token: ""