replicaCount: 1

image: ghcr.io/bookablecom/config-server:1.1.0

fullnameOverride: "config-server"
name: "config-server"

mesh:
  enabled: true

serviceAccount:
  create: true

service:
  type: ClusterIP
  port: 8080

github:
  username: 
  password: 