replicaCount: 1

image: ghcr.io/bookablecom/config-server:2.2.2

fullnameOverride: "config-server"
name: "config-server"

spring:
  profiles:
    active: vault,git

mesh:
  enabled: true

serviceAccount:
  create: true

service:
  type: ClusterIP
  port: 8080

github:
  repo: https://github.com/bookablecom/configurations
  secret:
    name: config-server-github-secret
    create: false
    username: ""
    password: ""
vault: 
  host: vault.vault.svc.cluster.local
  secret:
    name: config-server-vault-secret
    create: false
    token: ""
