{{- if .Values.keycloak.admin.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.keycloak.admin.secret.name }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.name }}
type: "Opaque"
stringData:
  KEYCLOAK_USER: {{ .Values.keycloak.admin.secret.keycloakUser }}
  KEYCLOAK_PASSWORD: {{ .Values.keycloak.admin.secret.keycloakPassword }}
{{- end }}