apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-admin-user-secret
  annotations:
    kubernetes.io/service-account.name: {{ .Values.name }}
type: "Opaque"
stringData:
  KEYCLOAK_USER: {{ .Values.admin.keycloakUser }}
  KEYCLOAK_PASSWORD: {{ .Values.admin.keycloakPassword }}