{{- if .Values.db.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-db-secret
  annotations:
    kubernetes.io/service-account.name: {{ .Values.name }}
type: "Opaque"
stringData:
  DB_VENDOR: {{ .Values.db.secret.vendor }}
  DB_ADDR: {{ .Values.db.secret.host }}
  DB_USER: {{ .Values.db.secret.user }}
  DB_PASSWORD: {{ .Values.db.secret.password }}
  DB_DATABASE: {{ .Values.db.secret.database }}
{{- end }}