apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-db-secret
  annotations:
    kubernetes.io/service-account.name: {{ .Values.name }}
type: "Opaque"
stringData:
  DB_VENDOR: {{ .Values.db.vendor }}
  DB_ADDR: {{ .Values.db.host }}
  DB_USER: {{ .Values.db.user }}
  DB_PASSWORD: {{ .Values.db.password }}
  DB_DATABASE: {{ .Values.db.database }}