apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ .Chart.Name }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: https
              containerPort: 8443
              protocol: TCP
          volumeMounts:
            - name: keycloak-plugin
              mountPath: /opt/jboss/keycloak/standalone/deployments/keycloak-to-rabbit-2.1.jar
              subPath: keycloak-to-rabbit-2.1.jar
          envFrom:
            - secretRef:
                name: {{ .Values.db.secret.name }}
            - secretRef:
                name: {{ .Values.keycloak.admin.secret.name }}
            - configMapRef:
                name: keycloak-config
      volumes:
        - name: keycloak-plugin
          configMap:
            name: keycloak-plugin