{{- if .Values.ingress.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Chart.Name }}-route
spec:
  entryPoints:
    - web
  routes:
  - match: {{ .Values.ingress.match }}
    kind: Rule
    services:
    - name: {{ .Chart.Name }}
      port: {{ .Values.service.port }}
{{- end}}