{{- if .Values.vault.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  annotations:
    kubernetes.io/service-account.name: {{ include "vault-unseal-cronjob.serviceAccountName" . }}
type: "Opaque"
stringData:
  VAULT_ADDRESS: {{ .Values.vault.secret.vaultAddress }}
  VAULT_SHARD_1: {{ .Values.vault.secret.shard1 }}
  VAULT_SHARD_2: {{ .Values.vault.secret.shard2 }}
  VAULT_SHARD_3: {{ .Values.vault.secret.shard3 }}
{{- end }}