spring-boot:
  nameOverride: "user-service"
  fullnameOverride: "user-service"
  image:
    repository: ghcr.io/bookablecom/user-service
    tag: 1.5.24
  imagePullSecrets:
    - name: "dockerconfigjson-github-com"
  extraEnv:
    CONFIG_SERVER_URI: http://config-server:8080
  name: user-service
  healthChecks:
    enabled: false
    readinessProbe:
      httpGet:
        path: /actuator/health/readiness
        port: http
        httpHeaders:
          - name: authorization
      value: "Bearer xxx"
      initialDelaySeconds: 120
      periodSeconds: 40
      timeoutSeconds: 15
      failureThreshold: 60
    livenessProbe:
      httpGet:
        path: /actuator/health/liveness
        port: http
        httpHeaders:
          - name: authorization
            value: "Bearer xxx"
      initialDelaySeconds: 120
      periodSeconds: 40
      timeoutSeconds: 15
      failureThreshold: 60
  replicaCount: 1
  spring:
    profiles:
      active: default
traefik-ingress:
  ingress:
    match: "Host(`api.bsgrd.com`) && Path(`/users`, `/users/{id}`, `/organizations/{id}/users`)"
    tls:
      enabled: true
      resolver: "letsencrypt"
  service:
    name: "user-service"
    port: 8080

  middlewares:
    - namespace: default
      name: cors-headers
