replicaCount: 1

image:
  repository: docker.pkg.github.com/bookablecom/container-images/user-service
  pullPolicy: IfNotPresent
  tag: "1.0-SNAPSHOT"

fullnameOverride: "user-service"

serviceAccount:
  create: true

service:
  type: ClusterIP
  port: 8080