replicaCount: 1

image:
  repository: ghcr.io/bookablecom/user-service
  pullPolicy: IfNotPresent
  tag: "1.2-SNAPSHOT"

fullnameOverride: "user-service"

serviceAccount:
  create: true

service:
  type: ClusterIP
  port: 8080