apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
subsets:
  - addresses:
      - ip: {{ .Values.ip }}
    ports:
      - port: {{ .Values.service.port }}