apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: 1
  serviceName: {{ .Values.name }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: postgres:9.6.22-stretch
        ports:
          - containerPort: 5432
        env:
        - name: "POSTGRES_PASSWORD"
          value: "postgres"
        volumeMounts:
        - name: custom-init-scripts
          mountPath: /docker-entrypoint-initdb.d/
        - name: postgres-pvc
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: custom-init-scripts
        configMap:
          name: init-db
      - name: postgres-pvc
        persistentVolumeClaim:
          claimName: postgres-pvc