{{- if .Values.db.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-db-secret
  annotations:
    kubernetes.io/service-account.name: {{ .Values.name }}
type: "Opaque"
stringData:
  DB_PASSWORD: {{ .Values.db.password }}
{{- end}}