apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector: 
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      serviceAccountName: {{ .Values.name }}
      {{- if .Values.imagePullSecret.enabled }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret.secretName }}
      {{- end}}
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
          {{- end}}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
          {{- end}}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: local

          {{- if .Values.db.enabled }}
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-db-secret
                  key: DB_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-db-secret
                  key: DB_PASSWORD

            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-db-secret
                  key: DB_NAME

            - name: DB_HOST
              value: "postgres-service.postgres.svc.cluster.local"
          {{- end}}

          {{- if .Values.configserver.enabled }}
            - name: CONFIG_SERVER_URI
              value: {{ .Values.configserver.uri }}
          {{- end}}
          {{- if .Values.rabbitmq.enabled }}
            - name: RABBIT_HOST
              value: {{ .Values.rabbitmq.host }}
              
            - name: RABBIT_PORT
              value: "{{ .Values.rabbitmq.port }}"
          {{- end}}
            
            - name: JAEGER_URL
              value: "http://jaeger.linkerd-jaeger:14268/api/traces"