{{- if .Values.ingress.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.name }}-route
spec:
  entryPoints:
    - websecure
  routes:
    - match: {{ .Values.ingress.match }}
      kind: Rule
      services:
        - name: {{ .Values.name }}
          kind: TraefikService
  tls:
    certResolver: letsencrypt
{{- end}}
