spring-boot:
  nameOverride: "resource-service"
  fullnameOverride: "resource-service"
  image:
    repository: ghcr.io/bookablecom/resource-service
    tag: 0.0.18
  imagePullSecrets:
    - name: "dockerconfigjson-github-com"
  extraEnv:
    CONFIG_SERVER_URI: http://config-server:8080
  name: resource-service
  healthChecks:
    enabled: false
    readinessProbe:
      httpGet:
        path: /actuator/health/readiness
        port: http
      httpHeaders:
        - name: authorization
          value: ""
      initialDelaySeconds: 120
      periodSeconds: 40
      timeoutSeconds: 15
      failureThreshold: 60
    livenessProbe:
      httpGet:
        path: /actuator/health/liveness
        port: http
      httpHeaders:
        - name: authorization
          value: ""
      initialDelaySeconds: 120
      periodSeconds: 40
      timeoutSeconds: 15
      failureThreshold: 600
  replicaCount: 1
  spring:
    profiles:
      active: default
traefik-ingress:
  ingress:
    match: "Host(`api.bsgrd.com`) && Path(`/resources`, `/resources/{id}`, `/organizations/{id}/resources`, `/organizations/{id}/resources/{resId}`, `/organizations/{id}/resourceTypes`)"
    tls:
      enabled: true
      resolver: "letsencrypt"
  service:
    name: "resource-service"
    port: 8080
