traefik:
  additionalArguments:
    - "--certificatesresolvers.letsencrypt.acme.email=kasper.bisgaard@live.com"
    - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
    - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
    - "--entrypoints.web.http.redirections.entryPoint.to=:443"
    - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
    - "--api.dashboard=true"
    - "--log.level=INFO"
    - "--providers.kubernetesingress.ingressclass=traefik-internal"
    - "--experimental.plugins.cors.modulename=github.com/quintinheard/traefik-cors"
    - "--experimental.plugins.cors.version=v0.1.0"
    #--serversTransport.insecureSkipVerify=true
  dashboard:
    enabled: true
  rbac:
    enabled: true
  nodeSelector:
    node-type: master
  deployment:
    additionalVolumes:
      - name: plugins
        emptyDir: {}
  additionalVolumeMounts:
    - name: plugins
      mountPath: /plugins-storage
