replicaCount: 1

image: koolwithk/keycloak-arm:16.0.0

name: keycloak

serviceAccount:
  create: true

db:
  secret:
    create: false
    name: keycloak-db-secret
    vendor: postgres
    host: postgres.postgres.svc.cluster.local
    user: "keycloak"
    password: "keycloak"
    database: "keycloak"

keycloak:
  admin:
    secret:
      create: false
      name: keycloak-admin-user-secret
      keycloakUser: ""
      keycloakPassword: ""

ingress:
  enabled: true
  match: Host(`auth.bsgrd.com`)

service:
  type: ClusterIP
  port: 8443