replicaCount: 1

image: richardjkendall/keycloak-arm

name: "keycloak"

serviceAccount:
  create: true

db:
  enabled: true
  username: keycloak
  password: 
  dbname: keycloak

admin:
  username: user
  password: 

service:
  type: ClusterIP
  port: 8080