replicaCount: 1

image: koolwithk/keycloak-arm:16.0.0

name: keycloak

serviceAccount:
  create: true

db:
  vendor: postgres
  host: postgres.postgres.svc.cluster.local
  user: ""
  password: ""
  database: keycloak

admin:
  keycloakUser: ""
  keycloakPassword: ""

ingress:
  enabled: true
  match: Host(`auth.bsgrd.com`)

service:
  type: ClusterIP
  port: 8443