replicaCount: 1

image: ghcr.io/bookablecom/keycloak:1.0.3

name: keycloak

serviceAccount:
  create: true

db:
  enabled: true
  host: postgres.default.svc.cluster.local
  username: keycloak
  password: keycloak
  dbname: keycloak

ingress:
  enabled: true
  match: Host(`auth.bsgrd.com`)

admin:
  username: ""
  password: ""

service:
  type: ClusterIP
  port: 8080