replicaCount: 1

image:
  repository: ghcr.io/bookablecom/pact-broker
  pullPolicy: IfNotPresent
  tag: "1.0.2"

imagePullSecrets:
  - name: "dockerconfigjson-github-com"
nameOverride: "pact-broker"
fullnameOverride: "pact-broker"

serviceAccount:
  create: true
  annotations: {}
  name: ""

envFrom:
  - configMapRef:
      name: pact-broker-env

env:
  - name: PACT_BROKER_DATABASE_USERNAME
    valueFrom:
      secretKeyRef:
        name: pact.bookable-cluster.credentials.postgresql.acid.zalan.do
        key: username
        optional: false
  - name: PACT_BROKER_DATABASE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: pact.bookable-cluster.credentials.postgresql.acid.zalan.do
        key: password
        optional: false

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 9292

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
