spring-boot:
  nameOverride: "organization-service"
  fullnameOverride: "organization-service"
  image:
    repository: ghcr.io/bookablecom/organization-service
    tag: 1.13.15
  imagePullSecrets:
    - name: "dockerconfigjson-github-com"
  extraEnv:
    CONFIG_SERVER_URI: http://config-server:8080
  name: organization-service
  healthChecks:
    readinessProbe:
      httpGet:
        path: /actuator/health/readiness
        port: http
      httpHeaders:
        - name: authorization
          value: ""
      initialDelaySeconds: 120
      periodSeconds: 40
      timeoutSeconds: 15
      failureThreshold: 60
    livenessProbe:
      httpGet:
        path: /actuator/health/liveness
        port: http
      httpHeaders:
        - name: authorization
          value: ""
      initialDelaySeconds: 120
      periodSeconds: 40
      timeoutSeconds: 15
      failureThreshold: 60
  replicaCount: 1
  spring:
    profiles:
      active: default
traefik-ingress:
  ingress:
    match: "Host(`api.bsgrd.com`) && Path(`/organizations`, `/organizations/{id}`, `/organizations/{id}/invitations`, `/invitations`, `/invitations/{id}`)"
    tls:
      enabled: true
      resolver: "letsencrypt"
  service:
    name: "organization-service"
    port: 8080
