spring-boot:
  nameOverride: "organization-service"
  fullnameOverride: "organization-service"
  image:
    repository: ghcr.io/bookablecom/organization-service
    tag: 1.13.22
  imagePullSecrets:
    - name: "dockerconfigjson-github-com"
  extraEnv:
    CONFIG_SERVER_URI: http://config-server:8080
  name: organization-service
  healthChecks:
    enabled: false
    readinessProbe: {}
    livenessProbe: {}
  replicaCount: 1
  spring:
    profiles:
      active: default
traefik-ingress:
  ingress:
    match: "Host(`api.bsgrd.com`) && Path(`/organizations`, `/organizations/{id}`, `/organizations/{id}/invitations`, `/invitations`, `/invitations/{id}`)"
    tls:
      enabled: true
      resolver: "letsencrypt"
  service:
    name: "organization-service"
    port: 8080

  middlewares:
    - namespace: default
      name: cors-headers
