replicaCount: 1

image:
  repository: ghcr.io/bookablecom/organization-service
  pullPolicy: IfNotPresent
  tag: "1.9-SNAPSHOT"

fullnameOverride: "organization-service"

serviceAccount:
  create: true

service:
  type: ClusterIP
  port: 8080