apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: "artifactory.bsgrd.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: artifactory
            port:
              number: 8081
