apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-service
spec:
  replicas: 1
  serviceName: postgres-service
  selector:
    matchLabels:
      app: postgres-service
  template:
    metadata:
      labels:
        app: postgres-service
    spec:
      containers:
      - name: postgres-service
        image: postgres:9.6.22-stretch
        ports:
          - containerPort: 5432
        env:
        - name: "POSTGRES_PASSWORD"
          value: "postgres"
        volumeMounts:
        - name: custom-init-scripts
          mountPath: /docker-entrypoint-initdb.d/
      volumes:
      - name: custom-init-scripts
        configMap:
          name: init-db