apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ .Chart.Name }}
      imagePullSecrets:
        - name: dockerconfigjson-github-com
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          #livenessProbe:
          #  httpGet:
          #    path: /actuator/health/liveness
          #    port: 8080
          #  initialDelaySeconds: 3
          #  periodSeconds: 3
          #readinessProbe:
          #  httpGet:
          #    path: /actuator/health/readiness
          #    port: 8080
          #  initialDelaySeconds: 3
          #  periodSeconds: 3
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: organization-service-db-secret
                  key: DB_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: organization-service-db-secret
                  key: DB_PASSWORD

            - name: CONFIG_SERVER_URI
              value: http://config-server.default.svc.cluster.local:8080

            - name: DB_NAME
              value: organizationsvc

            - name: DB_HOST
              value: postgres-service.postgres.svc.cluster.local

            - name: RABBIT_HOST
              value: rabbitmq.rabbitmq.svc.cluster.local
              
            - name: RABBIT_PORT
              value: "5672"