apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: rabbitmq
    - protocol: TCP
      port: {{ .Values.management.port }}
      targetPort: {{ .Values.management.port }}
      name: rabbitmq-man