apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: 1
  serviceName: rabbitmq
  selector:
    matchLabels:
      app: rabbitmq
  
  template:
    metadata:
      {{- if .Values.mesh.enabled }}
      annotations:
        linkerd.io/inject: enabled
      {{- end}}
      labels:
        app: rabbitmq
    spec:
      serviceAccountName: {{ .Values.namespace.name }}
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
          - containerPort: {{ .Values.management.port }} 
            name: rabbitmq-man
          - containerPort: {{ .Values.service.port }} 
            name: rabbitmq
        env:
        - name: "RABBITMQ_ERLANG_COOKIE"
          value: "1WqgH8N2v1qDBDZDbNy8Bg9IkPWLEpu79m6q+0t36lQ="
        volumeMounts:
        - name: rabbitmq-conf
          mountPath: /etc/rabbitmq/rabbitmq.conf
          subPath: rabbitmq.conf
        - name: rabbitmq-definitions
          mountPath: /etc/rabbitmq/definitions.json
          subPath: definitions.json
        - mountPath: /var/lib/rabbitmq
          name: rabbitmq-pvc
      volumes:
        - name: rabbitmq-conf
          configMap:
            name: rabbitmq-conf
        - name: rabbitmq-definitions
          configMap:
            name: rabbitmq-definitions
        - name: rabbitmq-pvc
          persistentVolumeClaim:
            claimName: rabbitmq-pvc