apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata: 
  name: user-service-route
  namespace: default
spec:
  entrypoints:
    - web
  routes:
    - match: Host(`api.bsgrd.com`) && PathPrefix(`/users`)
      kind: Rule
      services:
        - name: user-service
          port: 8080