apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      restartPolicy: OnFailure
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret.secretName }}
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: {{ .Values.spring.profiles.active }}
        {{- if .Values.configserver.enabled }}
          - name: CONFIG_SERVER_URI
            value: {{ .Values.configserver.uri }}
        {{- end}}