replicaCount: 1

image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: 
  - name: ""

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8080

healthChecks:
  enabled: true
  readinessProbe:
    initialDelaySeconds: 600
    periodSeconds: 40
    timeoutSeconds: 15
    failureThreshold: 60
  livenessProbe:
    initialDelaySeconds: 1500
    periodSeconds: 30
    timeoutSeconds: 15
    failureThreshold: 60

ingress:
  enabled: true
  match: "" #Host(`api.bsgrd.com`) && PathPrefix(`/`)
  annotations: {}
  tls: 
    enabled: true
    resolver: "" #letsencrypt

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
