replicaCount: 1

image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets:
  - name: ""

nameOverride: ""
fullnameOverride: ""

extraEnv: {}
serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8080

healthChecks:
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: http
    httpHeaders:
      - name: authorization
        value: ""
    initialDelaySeconds: 120
    periodSeconds: 40
    timeoutSeconds: 15
    failureThreshold: 60
  livenessProbe:
    path: /actuator/health/liveness
    port: http
    httpHeaders:
      - name: authorization
        value: ""
    initialDelaySeconds: 120
    periodSeconds: 40
    timeoutSeconds: 15
    failureThreshold: 60
resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
